[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[server]
headless = true
port = 8501
address = "localhost"
enableXsrfProtection = true
sslCertFile = ".streamlit/certs/localhost.pem"
sslKeyFile = ".streamlit/certs/localhost-key.pem"
