[[pages]]
path = "app.py"
name = "ì•ˆë‚´"
icon = "ğŸ«"

[[pages]]
path = "pages/1_í•™ë¶€ëª¨_í˜ì´ì§€.py"
name = "í•™ë¶€ëª¨ í˜ì´ì§€"
icon = "ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦"

[[pages]]
path = "pages/2_ê´€ë¦¬ì_ìŠ¹ì¸_í˜ì´ì§€.py"
name = "ê´€ë¦¬ì ìŠ¹ì¸ í˜ì´ì§€"
icon = "âœ…"

[[pages]]
path = "pages/3_ê´€ë¦¬_í˜ì´ì§€.py"
name = "ê´€ë¦¬ í˜ì´ì§€"
icon = "âš™ï¸"
